language: ruby
script: bundle exec middleman build

env:
  global:
    - GIT_COMMITTER_NAME='suitougreentea'
    - GIT_COMMITTER_EMAIL='suitougreentea@noreply.github.com'
    - GIT_AUTHOR_NAME='suitougreentea'
    - GIT_AUTHOER_EMAIL='suitougreentea@noreply.github.com'
    - secure: "J2xR9pz65BrxWG/eeV77qTCn5CoVZqHj0mWd65LMfP5dpH7OqsN6Rd3zNqm4rQGzZNfj/x5LY6fWh+jRZ1vyKnpDGLUEPWN6VWE/MoDp7q/37TtVHfrRg10tXzghVKFM/isqUepadNJymMVB8DJ/zqMT0MTvMF8Exygf34zHYM8="

before_script:
  - echo beforescript

after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy 2> /dev/null'
